### ISSUE TITLE
[通知优化图标适配反馈]屏幕录制（重绘）

### ISSUE THREAD

**Issue by AzusaHana** [fankes/ColorOSNotifyIcon#10]
**需要适配的 APP 名称/包名/通知图标颜色 (必填)**

* 屏幕录制 / com.oplus.screenrecorder /#ec3e50

**提供相关 APP 的下载渠道截图以及简要说明用途 (必填)**

* 应该是C12或者OOS12内置的，屏幕录制，重绘一个跟图标一样的，还有颜色修正

* “com.coloros.screenrecorder” 这个是C11内置的，但没有apk画不了

**提供相关 APP 的通知单色图标适配素材 大小 50x50 (选填)**

* ![画面録画_12 11 16](https://user-images.githubusercontent.com/100906636/156956609-382a6c23-b5fd-40ce-869a-134b609374a8.png)

原图标
![画面録画_12 11 16(1)](https://user-images.githubusercontent.com/100906636/156956631-31f70b3a-a640-4e87-ada4-8af0056ec50c.png)

**Comment by fankes** [comment]
@pzcn 大佬有时间看看
