### ISSUE TITLE
[通知优化图标适配反馈]哈啰出行

### ISSUE THREAD

**Issue by AzusaHana** [fankes/ColorOSNotifyIcon#11]
**需要适配的 APP 名称/包名/通知图标颜色 (必填)**

* 哈啰出行/com.jingyao.easybike/#ff04a5eb

**提供相关 APP 的下载渠道截图以及简要说明用途 (必填)**

* 
![IT~`5C%Q9HR~~~SH3FO`FCF](https://user-images.githubusercontent.com/100906636/159118468-6e03b8d5-b22a-4e45-ae35-c4208603c632.jpg)

**提供相关 APP 的通知单色图标适配素材 大小 50x50 (选填)**

* 
![1](https://user-images.githubusercontent.com/100906636/159118504-543abe3d-5dcf-47a1-a093-3eb021cb2d09.png)

**Comment by fankes** [comment]
……你不能自己提交pr吗，你不是提交过pr吗

**Comment by fankes** [comment]
适配了
