### ISSUE TITLE
[通知优化图标适配反馈]

### ISSUE THREAD

**Issue by DearJing** [fankes/ColorOSNotifyIcon#13]
**飞鸟下载器com.feiniaobt黑色** 

**
![android_qr](https://user-images.githubusercontent.com/102679294/160864874-1605466f-75ba-4640-9e22-795cc2709291.png)
**

* 

**
![feiniaobt](https://user-images.githubusercontent.com/102679294/160864379-0ed2a47f-38c2-4f59-9bff-38727ae3c0d8.png)

**Comment by fankes** [comment]
请提供单色图标

**Comment by DearJing** [comment]
大佬，我不会制作单色图标

**Comment by fankes** [comment]
已适配
