### ISSUE TITLE
[问题与 BUG 反馈] 状态栏及下拉界面DPI变小

### ISSUE THREAD

**Issue by XiangNorth** [fankes/ColorOSNotifyIcon#14]
**系统版本(必填)**

* IN2020_11_C.03

**系统类型(请保留一个)**

* ColorOS

**Android 版本(必填)**

* 12

**模块版本(必填)**

* 1.5&1.51

**使用的 Xposed 框架名称与框架版本(必填)**

* LSPosed Zygisk 1.80(6482)

**同时使用的带有系统界面作用域的 Xposed 模块(选填)**

* 系统界面(com.android.systemui)

**问题的具体描述**

* 从 `1.5` 版本开始出现此问题
* 复现条件为**安装应用后(添加或升级)**
* 个人猜测与*动态刷新用户界面*或*设备为2k分辨率*有关

![reapper](https://user-images.githubusercontent.com/54651817/161285005-004f47d4-dbed-4a39-b3a0-4c380217105b.jpg)

**提供模块问题 Log 或必要 Log**

* (LSPosed 可在日志管理中查看并筛选包含 `ColorOSNotifyIcon` 的日志)

<details><summary>展开查看</summary><pre><code>

不熟悉 `LSPosed` 的日志筛选处理，抱歉。

</code></pre></details>

**Comment by Xnor-bear** [comment]
没注意第 6 项的标题，在此补上。

**同时使用的带有系统界面作用域的 Xposed 模块(选填)**

* 墨·状态栏歌词(statusbar.lyric)
* ColorOSTool(com.oosl.colorostool)(?)

**Comment by fankes** [comment]
这个是你的系统问题，我使用的最新版本12.1 C61 没有这个问题

**Comment by fankes** [comment]
动态刷新页面不会影响系统 DPI ，建议更新到最新版本的系统再试

**Comment by fankes** [comment]
请提供你的手机型号，以便核对问题，如果是一加系列应该是推送 12.1 了，更新一下试试

**Comment by Xnor-bear** [comment]
> 请提供你的手机型号，以便核对问题，如果是一加系列应该是推送 12.1 了，更新一下试试
> 据我之前自己的测试，系统本身就有 DPI 缩放的 BUG，多数情况下是手动在开发者选项中调整了“最小宽度”功能

- 手机型号为`一加 8 Pro`
- 暂时还没推送 ColorOS12.1
- 使用的是最新版本的模块(1.51)

是因为系统其他部分 DPI 未变化，只有状态栏部分偏大。
我这边测试一下再给您反馈。

**Comment by fankes** [comment]
> > 请提供你的手机型号，以便核对问题，如果是一加系列应该是推送 12.1 了，更新一下试试
> > 据我之前自己的测试，系统本身就有 DPI 缩放的 BUG，多数情况下是手动在开发者选项中调整了“最小宽度”功能
> 
> * 手机型号为`一加 8 Pro`
> * 暂时还没推送 ColorOS12.1
> * 使用的是最新版本的模块(1.51)
> 
> 是因为系统其他部分 DPI 未变化，只有状态栏部分偏大。 我这边测试一下再给您反馈。

你可以尝试，重启系统界面，然后开关启用通知图标优化，然后等待系统界面刷新后对比前后的通知栏大小

**Comment by fankes** [comment]
新版本已更新完毕，若问题依然存在，请再次反馈

**Comment by fankes** [comment]
由于您长时间没有回复，该问题视为已解决处理
