### ISSUE TITLE
[通知优化图标适配反馈]TIM

### ISSUE THREAD

**Issue by chagangzi** [fankes/ColorOSNotifyIcon#3]
**需要适配的 APP 名称/包名/通知图标颜色 (必填)**

* (示例：阅读/com.heytap.reader/#fff2a135)

* TIM/com.tencent.tim

**提供相关 APP 的下载渠道截图以及简要说明用途 (必填)**

* ![Screenshot_2022-03-01-08-34-22-69_97550f1d11c73369bbee8f7d47965447.jpg](https://user-images.githubusercontent.com/18086417/156082210-c7092cf0-689f-4725-b3db-07cad4032515.jpg)

**提供相关 APP 的通知单色图标适配素材 大小 50x50 (选填)**

* (可填写资源下载地址或直接添加附件提交，不接受百度网盘、天翼云盘以及各种快传、私有云盘)

* (若直接在附件提交这里可不填)

**Comment by fankes** [comment]
done
