### ISSUE TITLE
[通知优化图标适配反馈]

### ISSUE THREAD

**Issue by DearJing** [fankes/ColorOSNotifyIcon#39]
**115白色

com.ylmf.androidclient

**

*
115官网
![Screenshot_2022-06-30-11-26-00-27_01fe112b4868b651f115b37c3a196e04](https://user-images.githubusercontent.com/102679294/176586405-b9b1a824-842a-41e5-a64f-d4789c47d52c.jpg)

![ylmf_main](https://user-images.githubusercontent.com/102679294/176586511-ec9f6676-b41a-46da-b8fb-0c881d180b06.png)

**Comment by DearJing** [comment]
![Uploading ylmf_main.png…]()

**Comment by DearJing** [comment]
通知栏图标是数字5

**Comment by fankes** [comment]
它有没有图标问题_？_

**Comment by fankes** [comment]
ok了
