### ISSUE TITLE
[通知优化图标适配反馈]广东移动智慧生活

### ISSUE THREAD

**Issue by ghost** [fankes/ColorOSNotifyIcon#4]
**需要适配的 APP 名称/包名/通知图标颜色 (必填)**

* 广东移动智慧生活/com.kingpoint.gmcchh

**提供相关 APP 的下载渠道截图以及简要说明用途 (必填)**

* 
![Screenshot_2022-03-04-09-12-05-62_97550f1d11c73369bbee8f7d47965447](https://user-images.githubusercontent.com/13930719/156680137-3c8d9753-e07a-4515-ad87-f9c61688ff1e.jpg)
和已经适配的中国移动一样

**提供相关 APP 的通知单色图标适配素材 大小 50x50 (选填)**

* (可填写资源下载地址或直接添加附件提交，不接受百度网盘、天翼云盘以及各种快传、私有云盘)

* (若直接在附件提交这里可不填)

**Comment by fankes** [comment]
已适配
