### ISSUE TITLE
[通知优化图标适配反馈]

### ISSUE THREAD

**Issue by hmy65** [fankes/ColorOSNotifyIcon#40]
**需要适配的 APP 名称/包名/通知图标颜色 (必填)**

小米计算器/com.miui.calculator/橙白

**提供相关 APP 的下载渠道截图以及简要说明用途 (必填)**

https://play.google.com/store/apps/details?id=com.miui.calculator&hl=en&gl=US
ColorOS的计算器功能太差，只能用其他的。
弹出窗口时，状态栏会生成一个计算器浮窗的通知。

**提供相关 APP 的通知单色图标适配素材 大小 50x50 (选填)**

**Comment by fankes** [comment]
1.给它设置为不重要通知
2.把它的通知权限关掉

**Comment by hmy65** [comment]
好的 感谢~
