### ISSUE TITLE
[通知优化图标适配反馈]

### ISSUE THREAD

**Issue by 18591615351** [fankes/ColorOSNotifyIcon#41]
**需要适配的 APP 名称/包名/通知图标颜色 (必填)**

* realme社区/com.realmecomm.app/#FFD700

**提供相关 APP 的下载渠道截图以及简要说明用途 (必填)**

* 
![Screenshot_2022-07-12-10-52-22-18_9d6ca196173956b012958210db5a71fe](https://user-images.githubusercontent.com/88500210/178398306-81e10607-4479-4f94-81fd-c42597cd1597.jpg)
ColorOS软件商店下载

**提供相关 APP 的通知单色图标适配素材 大小 50x50 (选填)**

**Comment by fankes** [comment]
这又是什么套娃社区

**Comment by fankes** [comment]
已适配
