### ISSUE TITLE
[通知优化图标适配反馈]

### ISSUE THREAD

**Issue by chiyema** [fankes/ColorOSNotifyIcon#42]
**需要适配的 APP 名称/包名/通知图标颜色 (必填)**

* (示例：阅读/com.heytap.reader/#fff2a135)

* 懂球帝/com.dongqiudi.news/#00B330

**提供相关 APP 的下载渠道截图以及简要说明用途 (必填)**

* 
![Screenshot_2022-08-10-07-34-52-70_97550f1d11c73369bbee8f7d47965447](https://user-images.githubusercontent.com/8358253/183928937-58b1fbbd-d529-4eeb-aa61-31831df7d374.jpg)
可从酷安下载。懂球帝是中文足球资讯app

**提供相关 APP 的通知单色图标适配素材 大小 50x50 (选填)**

* (可填写资源下载地址或直接添加附件提交，不接受百度网盘、天翼云盘以及各种快传、私有云盘)

* (若直接在附件提交这里可不填)

**Comment by fankes** [comment]
@NekoMua

**Comment by fankes** [comment]
@NekoMua
