### ISSUE TITLE
[通知优化图标适配反馈]

### ISSUE THREAD

**Issue by chiyema** [fankes/ColorOSNotifyIcon#43]
**需要适配的 APP 名称/包名/通知图标颜色 (必填)**

* (示例：阅读/com.heytap.reader/#fff2a135)

* 直播吧/android.zhibo8/#1B8FE6

**提供相关 APP 的下载渠道截图以及简要说明用途 (必填)**

* 
![Screenshot_2022-08-10-20-27-36-81_97550f1d11c73369bbee8f7d47965447](https://user-images.githubusercontent.com/8358253/184060434-250e79ca-3b01-4132-808f-d43ad20386b2.jpg)
直播吧可在酷安下载，是国内足球篮球相关资讯的 app。谢谢适配！

**提供相关 APP 的通知单色图标适配素材 大小 50x50 (选填)**

* (可填写资源下载地址或直接添加附件提交，不接受百度网盘、天翼云盘以及各种快传、私有云盘)

* (若直接在附件提交这里可不填)

**Comment by fankes** [comment]
@NekoMua
