### ISSUE TITLE
[通知优化图标适配反馈]

### ISSUE THREAD

**Issue by GreatAden** [fankes/ColorOSNotifyIcon#47]
**需要适配的 APP 名称/包名/通知图标颜色 (必填)**
剪映 com.lemon.lv 通知图标应该是黑白的吧

**提供相关 APP 的下载渠道截图以及简要说明用途 (必填)**
在酷安下载的，用来剪视频，在任务栏显示的是空白图标
![Screenshot_2022-08-12-20-15-48-60_b783bf344239542886fee7b48fa4b892](https://user-images.githubusercontent.com/89302318/184353773-c99b5f22-ab54-4f6b-8cff-d7de32afeba1.jpg)
望修复
*

**Comment by fankes** [comment]
@NekoMua
规则开启全部替换
