### ISSUE TITLE
[通知优化图标适配反馈]

### ISSUE THREAD

**Issue by SAFEluren** [fankes/ColorOSNotifyIcon#50]
**需要适配的 APP 名称/包名/通知图标颜色 (必填)**

蔚来校园，com.a9second.weilaixi.wlx，#FF1B9BCA

**提供相关 APP 的下载渠道截图以及简要说明用途 (必填)**
![Screenshot_2022-09-13-13-04-27-90_df198e732186825c8df26e3c5a10d7cd.jpg](https://user-images.githubusercontent.com/79032826/189813522-2d7e33db-8daf-4bd4-98ef-c98e0ec034e9.jpg)

智能校园设备使用

* 

**提供相关 APP 的通知单色图标适配素材 大小 50x50 (选填)**

* (可填写资源下载地址或直接添加附件提交，不接受百度网盘、天翼云盘以及各种快传、私有云盘)

https://appdownload.iweilaixi.com/

**Comment by fankes** [comment]
@NekoMua
