### ISSUE TITLE
[通知优化图标适配反馈]

### ISSUE THREAD

**Issue by SAFEluren** [fankes/ColorOSNotifyIcon#51]
**需要适配的 APP 名称/包名/通知图标颜色 (必填)**

爱山东/com.hanweb.android.sdzwfw.activity/#C90C04

**提供相关 APP 的下载渠道截图以及简要说明用途 (必填)**
![Screenshot_2022-09-15-07-34-36-38_df198e732186825c8df26e3c5a10d7cd.jpg](https://user-images.githubusercontent.com/79032826/190281509-8322f0e6-fe09-4b45-a042-bdc291b3a15b.jpg)
山东省政务相关

**提供相关 APP 的通知单色图标适配素材 大小 50x50 (选填)**

![1663199086168.png](https://user-images.githubusercontent.com/79032826/190281695-5ff2c2d3-35f7-4e66-b91c-bdf16361902f.png)

下载链接：http://isdapp.shandong.gov.cn/jmopen/webapp/html5/fx/index.html

**Comment by fankes** [comment]
@NekoMua
