### ISSUE TITLE
[通知优化图标适配反馈]

### ISSUE THREAD

**Issue by Cai231** [fankes/ColorOSNotifyIcon#52]
**需要适配的 APP 名称/包名/通知图标颜色 (必填)**
* 完美世界电竞/com.pwrd.steam.esports/#000000

**提供相关 APP 的下载渠道截图以及简要说明用途 (必填)**

* 各大应用商店都能下载，CSGO完美平台的官方游戏社区app，类似王者营地

**提供相关 APP 的通知单色图标适配素材 大小 50x50 (选填)**

* (可填写资源下载地址或直接添加附件提交，不接受百度网盘、天翼云盘以及各种快传、私有云盘)

* (若直接在附件提交这里可不填)

**Comment by Cai231** [comment]
![Uploading Screenshot_2022-09-22-12-30-06-92_97550f1d11c73369bbee8f7d47965447.jpg…]()

**Comment by Cai231** [comment]
![Screenshot_2022-09-22-12-30-06-92_97550f1d11c73369bbee8f7d47965447](https://user-images.githubusercontent.com/95583648/191664834-8f7666f9-0147-4aa4-b6e7-1e1a7547fcb3.jpg)

**Comment by fankes** [comment]
@NekoMua
