### ISSUE TITLE
[通知图标优化适配反馈]

### ISSUE THREAD

**Issue by jiangyuhan13** [fankes/ColorOSNotifyIcon#58]
### APP 名称

一木清单

### APP 包名

com.wangc.todolist

### 下载渠道、来源地址链接

酷安，或者各大手机软件商店均提供下载

### 简单描述适配的通知图标使用场景

该App在状态栏的通知图标始终是彩色的，因为它是最近新出的一款软件，由于是清单类软件，所以通知也比较多，彩色的话，比较不舒服。在此求大大适配通知图标，非常感谢！

### 通知单色图标适配素材 (大小 50x50~72x72)

![一木清单_1 3 0](https://user-images.githubusercontent.com/102824661/206894115-3c174592-2a6c-41a6-ba92-77edf66c8c7c.png)

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
