### ISSUE TITLE
[通知优化图标适配反馈]信息（一加）

### ISSUE THREAD

**Issue by AzusaHana** [fankes/ColorOSNotifyIcon#6]
**需要适配的 APP 名称/包名/通知图标颜色 (必填)**

*信息（一加）/ com.android.mms / #30d391

**提供相关 APP 的下载渠道截图以及简要说明用途 (必填)**

* 一加内置，收发短信：原来适配的信息图标为橙色方形的，和一加的COS/氧OS12不一样

**提供相关 APP 的通知单色图标适配素材 大小 50x50 (选填)**

* 
![message](https://user-images.githubusercontent.com/100906636/156769808-d1378c3a-01ca-4d05-aee0-5f253737d241.png)

**Comment by fankes** [comment]
已适配
