### ISSUE TITLE
[通知图标优化适配反馈]

### ISSUE THREAD

**Issue by pgglove** [fankes/ColorOSNotifyIcon#61]
### APP 名称

零跑

### APP 包名

com.dahua.leapmotor

### 下载渠道、来源地址链接

各大应用商店

### 简单描述适配的通知图标使用场景

打开蓝牙钥匙常驻任务栏图标不统一

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
