### ISSUE TITLE
[通知优化图标适配反馈]电话本（联系人）

### ISSUE THREAD

**Issue by AzusaHana** [fankes/ColorOSNotifyIcon#7]
**需要适配的 APP 名称/包名/通知图标颜色 (必填)**

* 电话本（一加）/ com.android.contacts /#166ed2

**提供相关 APP 的下载渠道截图以及简要说明用途 (必填)**

* 内置系统软件，未接电话图标
![Screenshot_2022-03-04-21-24-04-40_b783bf344239542](https://user-images.githubusercontent.com/100906636/156771814-1cce42a4-6a5b-4456-b2e2-c0df8c846605.jpg)
![IMG_20220304_212359](https://user-images.githubusercontent.com/100906636/156771751-d285b099-6df2-4997-b529-10759947d5b3.jpg)

**提供相关 APP 的通知单色图标适配素材 大小 50x50 (选填)**

* 和原适配的电话图标一致，颜色不一样，一加的电话颜色也是#166ed2而不是绿色，如果能增加个选项就好了

**Comment by fankes** [comment]
由于 ColorOS 的混乱性，不会单独根据你们每个人的喜好去适配这些功能，如喜欢自定义请自行克隆项目自己改

**Comment by fankes** [comment]
新版本已加入可自定义规则地址，如果实在喜欢自定义可以fork项目自己修改颜色，然后把更新地址指向新的项目即可
