### ISSUE TITLE
[通知优化图标适配反馈]

### ISSUE THREAD

**Issue by Kimjaejiang** [fankes/ColorOSNotifyIcon#8]
**需要适配的 APP 名称/包名/通知图标颜色 (必填)**
APP:Link. 
包名:com.homelink.im
通知图标颜色:黑色
* (示例：阅读/com.heytap.reader/#fff2a135)

* 

**提供相关 APP 的下载渠道截图以及简要说明用途 (必填)**

* 公司软件，接受客户订单

**提供相关 APP 的通知单色图标适配素材 大小 50x50 (选填)**
无
* (可填写资源下载地址或直接添加附件提交，不接受百度网盘、天翼云盘以及各种快传、私有云盘)

* (若直接在附件提交这里可不填)

**Comment by fankes** [comment]
![0fbe4033f5765fae85a36d78d8698f7c.jpg](https://user-images.githubusercontent.com/37344460/156871206-202e5540-ea1b-42a3-bbba-5b3521ff0d73.jpg)
@pzcn
