### ISSUE TITLE
[通知优化图标适配反馈]电池

### ISSUE THREAD

**Issue by AzusaHana** [fankes/ColorOSNotifyIcon#9]
**需要适配的 APP 名称/包名/通知图标颜色 (必填)**

* 电池 / com.oplus.battery / #2dc84e

**提供相关 APP 的下载渠道截图以及简要说明用途 (必填)**

* 一加内置应用，充电时显示通知，其他系列的电池应用包名未知
![Screenshot_2022-03-06-00-03-18-07_fc704e6b13c4fb2](https://user-images.githubusercontent.com/100906636/156905131-e59e61e5-f946-4dca-9cd5-ae5bbe3d66fd.jpg)

**提供相关 APP 的通知单色图标适配素材 大小 50x50 (选填)**

* ![battery](https://user-images.githubusercontent.com/100906636/156905242-5e55de88-e647-4422-856f-c04f99aa66e6.png)

**Comment by fankes** [comment]
@pzcn ～～有时间看看
